version: '3'
services:
  app:
    build: .
    ports:
      - '5000:5000'
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    command: nodemon index.js
    volumes:
      - .:/app
    depends_on:
      - redis
  redis:
    image: redis
